apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devpod
  labels:
    app: devpod
spec:
  selector:
    matchLabels:
      app: devpod
  serviceName: devpod
  replicas: {{ ternary 1 0 .Values.enabled }}
  template:
    metadata:
      labels:
        app: devpod
    spec:
      terminationGracePeriodSeconds: 10
      #imagePullSecrets:
      #- name: diploi-pull-secret
      containers:
        - name: devpod
          image: ghcr.io/munkkeli/diploi-devpod-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 3000
            - containerPort: 3001
          env:
            {{ range $key, $val := .Values.parameterGroupsEnabled }}
            {{ if $val }}
            - name: parameter_group_{{ $key }}_enabled
              value: "1"
            {{ end }}
            {{ end }}
            {{- range .Values.env }}
            {{- if contains "app" .contexts }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
            {{- range .Values.parameterGroups }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
            - name: REPOSITORY_URL
              value: {{ .Values.repositories.app.url }}
            - name: REPOSITORY_BRANCH
              value: {{ .Values.repositories.app.branch }}
            - name: REPOSITORY_TAG
              value: {{ .Values.repositories.app.tag }}
            - name: APP_PUBLIC_URL
              value: {{ .Values.hosts.app }}
            - name: STAGE
              value: {{ .Values.stage }}
          volumeMounts:
            - name: app-mount
              mountPath: /app
            - name: root-mount
              mountPath: /root
            - name: ssh-keys
              mountPath: /etc/ssh/internal_ssh_host_rsa.pub
              subPath: internal_ssh_host_rsa.pub
            - name: diploi-git
              mountPath: /etc/diploi-git
      volumes:
        - name: app-mount
          hostPath:
            path: {{ .Values.storage.dev.hostPath }}
        - name: root-mount
          hostPath:
            path: {{ .Values.storage.devroot.hostPath }}
        - name: ssh-keys
          secret:
            secretName: ssh-keys
        - name: diploi-git
          secret:
            secretName: diploi-git
