apiVersion: v1
kind: Service
metadata:
  name: devpod
spec:
  ports:
    - port: 80
      name: app
    - port: 3000
      name: status
    - port: 3001
      name: editor
  selector:
    app: devpod
